---
- hosts: app
  become: yes
  gather_facts: no
  vars:
      git_repo_url: https://github.com/Alexklashitsky/bootcamp-app.git
      repo_path: /home/app/web
      repo_branch: master
  tasks: 
  - name: Run the equivalent of "apt-get update" as a separate step
    apt:
     update_cache: yes
  - name: Ansible shell module multiple commands
    shell: 'curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -'
  - name: Install reqired packages
    apt: name={{ item }} state=present
    with_items:
      - git
      - nodejs
  - name: Clone a private repository
    git:
      repo: "{{ git_repo_url }}"
      dest: "{{ repo_path }}"
        # version: "{{ repo_branch }}"
      accept_hostkey: yes
  - name: Build app
    command: sudo npm i
    args:
      chdir: "{{ repo_path }}"
  - name:  pm2 install
    npm:
      name: pm2 
      global: yes
  - name: start pm2 process
    command: sudo pm2 start /home/app/web/src/index.js
  # - name: make  me smile start at system restart
  #   become: true
  #   command: pm2 startup systemd -u app --hp /home/app
  # - name: systemd
  #   command: pm2 startup systemd
  # - name: path to save
  #   command: sudo env PATH=$PATH:/usr/bin /usr/lib/node_modules/pm2/bin/pm2 startup systemd -u app --hp /home/app
  # - name: save
  #   command: pm2 save

  

